### ISSUE TITLE
"Intermittent" exception running incremental source generator

### ISSUE THREAD

**Issue by eredmo** [mocklis/mocklis#19]
This is for v1.4.0-alpha.1:

Exception when running the incremental source generator. Looks to be isolated to some interfaces - i.e. not all interfaces cause the issue, but the ones that do, do so consistently.

Relevant part of stack trace:

```System.NullReferenceException: Object reference not set to an instance of an object.
      at Mocklis.MockGenerator.CodeGeneration.SymbolEquality.SameNamespace(INamespaceSymbol x, INamespaceSymbol y)
      at Mocklis.MockGenerator.CodeGeneration.SymbolEquality.SameType(ITypeSymbol x, ITypeSymbol y)
      at Mocklis.MockGenerator.CodeGeneration.SymbolEquality.SameParameter(IParameterSymbol x, IParameterSymbol y)
      at Mocklis.MockGenerator.CodeGeneration.SymbolEquality.SameArray[T](IReadOnlyList`1 x, IReadOnlyList`1 y, Func`3 comparer)
      at Mocklis.MockGenerator.CodeGeneration.SymbolEquality.MethodEquality.Equals(IMethodSymbol x, IMethodSymbol y)
      at Mocklis.MockGenerator.CodeGeneration.PropertyBasedMethodMock.Equals(PropertyBasedMethodMock other)
      at Mocklis.MockGenerator.CodeGeneration.ExtractedInterfaceInformation.Equals(ExtractedInterfaceInformation other)
      at Mocklis.MockGenerator.CodeGeneration.ExtractedClassInformation.Equals(ExtractedClassInformation other)
      at Microsoft.CodeAnalysis.NodeStateTable`1.Builder.GetModifiedItemAndState(T previous, T replacement, IEqualityComparer`1 comparer)```

**Comment by eredmo** [comment]
Resolve by coding a little bit more defensively in the SameNamespace method.

**Comment by eredmo** [comment]
Closing
